version: '3.8'
services:
 api:
  build: .
  container_name: faq_api
  ports:
    - "4000:4000"
  volumes:
    - .:/usr/src/app
  env_file:
    - .env
  depends_on:
  - mongodb
  - redis
 mongodb:
  image: mongo:6.0
  container_name: faq_mongo
  ports:
    - "27017:27017"
  volumes:
    - mongo_data:/data/db
 redis:
  image: redis:7.0
  container_name: faq_redis
  ports:
    - "6379:6379"
volumes:
 mongo_data: